
def li_lineage():
    """
    Representation of the ISO19115 lineage provenance description.
    Information about the events or source data used in constructing a dataset
    """
    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'is_document': True,
        'pstr': ('{}', ('name',)),
        'properties': [
            ('statement','str','0.1',
                'General explanation of the level of knowledge or lack thereof about the lineage'),
            ('process_step','iso.process_step','0.N',
                'How the resource was developed or set of events associated with production.'),
            ('source','iso.source','0.N','Input(s) used in production of resource')
        ],
        'constraints': []
    }


def process_step():
    """
    Representation of the ISO19115 LE_ProcessStep and parent LI_ProcessStep classes.
    """

    processor_doc = """Individual or organisation responsible for the process step.
    Use roleCode='processor'. Contact information is not necessary.
    """

    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'is_document': False,
        'pstr': ('{}', ('name',)),
        'properties': [
            ('description','str','1.1',
                'General description of the events in the development of the resource.'),
            ('rationale','str','0.1',
                'Purpose for performing the process on the resource'),
            ('step_datetime','time.datetime','0.1',
                'The date and time when the process was completed.'),
            ('processor','linked_to(shared.responsibility)','0.1', processor_doc),
            ('reference','shared.citation','0.N',
                'Process step documentation'),
            ('source', 'linked_to(data.dataset)','0.N',
                'Information on the inputs used in the process step.'),
            ('processing_information','iso.processing','0.N',
                'Comprehensive information on the processing carried out'),
            ('report','iso.process_step_report','0.N',
                'Report generated by the process step'),
            ]
    }


def processing():
    """
    Representation of the ISO19115 LE_Processing class

    # Note that the algorithm definition has been adjusted to be more generic
    # and less "instrument obsessed" than ISO19115. Name is an extension, and
    # the identifier is simply a code string (id) ... but given there may be
    # no identifier space for this processing step, it is made optional, rather
    # than mandatory as in ISO. For export to ISO, the recommendation is to
    # use the identifier of the CIM document which uses this class.

    """
    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'is_document': False,
        'pstr': ('{}', ('name',)),
        'properties': [
            ('name', 'str','1.1',
                'Name of the processing action (ISO extension)'),
            ('identifier','str','0.1',
                "Identifier (strictly, a code which can be used in an MD_Identifier"),
            ('softwareReference', 'linked_to(shared.citation)', '0.N',
                "Reference to document describing processing software"),
            ('procedureDescription','str','0.1',
                "additional details about the processing procedures"),
            ('documentation','linked_to(shared.citation)','0.1',
                "reference to documentation describing the processing"),
            ('runTimeParameters','str','0.1',
                "parameters to control the processing operations, entered at run time"),
            ('algorithm', 'iso.algorithm','0.N',
                "details of the methodology carried out in this processing")
            ]
    }


def process_step_report():
    """
    Report of what happened during a processing step.
    Representation of ISO LE_ProcessStepReport, modified to
    use links or body text, rather than files.
    """
    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'is_document': False,
        'pstr': ('{}', ('name',)),
        'properties': [
            ('name', 'str', '1.1',
                'Name of the processing report'),
            ('description', 'str', '1.1',
                'Summary textual description of what occurred during the process step'),
            ('link', 'shared.online_resource','0.1',
                'Link to actual report documents, if any')
        ]
    }


def algorithm():
    """ Representation of the LE_Algorithm Class"""
    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'is_document': False,
        'pstr': ('{}', ('description',)),
        'properties':[
            ('description','str','0.1',
                'Textural description of algorithm'),
            ('citation', 'linked_to(shared.citation)', '0.1',
                'Formal documentation for the algorithm used.')
        ]
    }